//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenSergeev1.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdSergeevEntities : DbContext
    { 
        private static bdSergeevEntities _context;
        public bdSergeevEntities()
            : base("name=bdSergeevEntities")
        {
        }
        public static bdSergeevEntities GetContext()
        {
            if (_context == null)
                _context = new bdSergeevEntities();
            return _context;
          }  
           
            
        

    
        
          
          

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KategoriiTovarov> KategoriiTovarov { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<Postavchiki> Postavchiki { get; set; }
        public virtual DbSet<Proizvoditeli> Proizvoditeli { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tovari> Tovari { get; set; }
    }
}
